### ISSUE TITLE
artefacts

### ISSUE THREAD

**Issue by pure-amber** [97Dima97/learning-programs#15]
https://github.com/97Dima97/learning-programs/blob/9e8f8e3c159c730c7a465075bc30b18bd123cf83/functions/getWordCount.js#L4

у тебя тут могут получиться элементы, состоящие из пустых строк
![image](https://github.com/97Dima97/learning-programs/assets/125300790/b49c7cbc-d91d-4893-b514-dbac0df5847a)
Фильтруй такие элементы после сплита через array.filter, их не должно быть в массиве

**Comment by 97Dima97** [comment]
used the filter method
