### ISSUE TITLE
words

### ISSUE THREAD

**Issue by pure-amber** [97Dima97/learning-programs#18]
https://github.com/97Dima97/learning-programs/blob/2a441c9fcc801ce0a02781b82a3746dfe25c9331/functions/getWordCount.js#L3C38-L3C57

а если символ % попадется, то тоже на пробел заменится?
зачем так называть переменную? Назвал бы просто words - переменная в виде множественного числа подразуумевается как список

**Comment by 97Dima97** [comment]
проверил на тестах (%) заменяется на пробел.
изменил имя переменной на одно слово .
