### ISSUE TITLE
strange returnng

### ISSUE THREAD

**Issue by pure-amber** [97Dima97/learning-programs#25]
https://github.com/97Dima97/learning-programs/blob/ed47e0979c1792dd4744688b206fac5dcc5821a1/functions/getTimeUtc.js#L5

а если эту функцию будет использовать другой модуль, то он что прям такую неожиданную строку и получит? Выбрасывай тут лучше exception. В сообщении исключения укажи, какие значения может принимать входной параметр offset

**Comment by 97Dima97** [comment]
поменял .
