### ISSUE TITLE
every test will be new separate function

### ISSUE THREAD

**Issue by pure-amber** [97Dima97/learning-programs#32]
https://github.com/97Dima97/learning-programs/blob/ed47e0979c1792dd4744688b206fac5dcc5821a1/functions.test.js#L19

давай для каждой функции будет писать отдельную тестовую функцию, а из этого файла будем их вызывать. Можешь складывать тестовые функции в отдельную директорию tests. Все по аналогии с директорией functions и ее содержимым

**Comment by 97Dima97** [comment]
сделал
