### ISSUE TITLE
why is localOffset?

### ISSUE THREAD

**Issue by pure-amber** [97Dima97/learning-programs#45]
https://github.com/97Dima97/learning-programs/blob/26439ecd3efa1846abc292db1c19cdac28331622/functions/getTimeUtcString.js#L13

зачем нужно получать локальное смещение? Не проще ли все операции выполнять с объектом Date в конце операции извлекать часы и минуты, и далее если нужно форматировать в a.m.?

**Comment by 97Dima97** [comment]
немного переписал .
