### ISSUE TITLE
separate function for condition

### ISSUE THREAD

**Issue by pure-amber** [97Dima97/learning-programs#51]
https://github.com/97Dima97/learning-programs/blob/26439ecd3efa1846abc292db1c19cdac28331622/functions/getTimeUtcString.js#L10

вынести `offset > maxOffset || offset < minOffset || offset !== ~~offset` в отдельную функцию назови ее так, что тут проверяешь

**Comment by 97Dima97** [comment]
вынес в отдельную функцию.
