### ISSUE TITLE
code duplication is not fixed

### ISSUE THREAD

**Issue by pure-amber** [97Dima97/learning-programs#60]
https://github.com/97Dima97/learning-programs/blob/2b39d5d828d56e4415461d70634226caba286169/functions/getTimeUtcString.js#L45

everything is very simple:
```
const minutesRaw = ...get minutes from object Date...
const minutes = minutesRaw < 10 ? `0${minutesRaw}`  : minutesRaw;
return `${hours}:${minutes}`; 
```

**Comment by 97Dima97** [comment]
убрал дублирование.
