### ISSUE TITLE
24:00 - this result is possible?

### ISSUE THREAD

**Issue by pure-amber** [97Dima97/learning-programs#77]
https://github.com/97Dima97/learning-programs/blob/b54e4514977e1580f9929b3930d8ba6f72f915c1/functions/getTimeUtcString.js#L36

**Comment by 97Dima97** [comment]
добавил отдельную переменную  с нужным количеством часов.

**Comment by pure-amber** [comment]
try to write code without using this new constant

**Comment by 97Dima97** [comment]
переписал без константы "23"
