### ISSUE TITLE
if hours = 24, then what will be?

### ISSUE THREAD

**Issue by pure-amber** [97Dima97/learning-programs#80]
https://github.com/97Dima97/learning-programs/blob/3103ba527486f53dd86302fc70b2d927059471df/functions/getTimeUtcString.js#L41

какое время будет в выходной строке, если hours получилось равным 24? Есть ли тесты на такой вариант?

**Comment by 97Dima97** [comment]
Так как время 00:00 = 24:00
есть тесты у которого на входе 0 то есть время рано 24:00 и на выходе 00:00
