### ISSUE TITLE
do restult without getHours, getMinutes

### ISSUE THREAD

**Issue by pure-amber** [97Dima97/learning-programs#81]
https://github.com/97Dima97/learning-programs/blob/3103ba527486f53dd86302fc70b2d927059471df/function.test/getTimeUtcString.test.js#L10

если ты мокаешь дату и уже знаешь ее значение, то зачем в методе .toBe получать часы и минуты из даты? Пиши сразу же строкой результат, что должно получиться. например '16:05'

**Comment by 97Dima97** [comment]
убрал лишние переменные .
оставил  только числа в .toBy
