### ISSUE TITLE
why is freee line here?

### ISSUE THREAD

**Issue by pure-amber** [97Dima97/learning-programs#84]
https://github.com/97Dima97/learning-programs/blob/3103ba527486f53dd86302fc70b2d927059471df/function.test/getTimeUtcString.test.js#L20-L23

можно более лаконично расписать:
```
expect(getTimeUtcString => getTimeUtcString(1.1))
    .toThrow();
```
Проверь, будет ли так работать

**Comment by 97Dima97** [comment]
сократил 
все работает.
