### ISSUE TITLE
what happens if you call a function without input parameters?

### ISSUE THREAD

**Issue by pure-amber** [97Dima97/learning-programs#85]
https://github.com/97Dima97/learning-programs/blob/3103ba527486f53dd86302fc70b2d927059471df/function.test/getTimeUtcString.test.js#L12

getTimeUtcString() - What will happen?
maybe add the ability to call without input parameters?

**Comment by 97Dima97** [comment]
Добавил условие
при отсутствие входных параметров будет возвращать время по смещению "UTC 0 "
